apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  SQL_SERVER: sqlservergik2194.database.windows.net
  SQL_USER: sqladmingIk2194
  SQL_PASSWORD: demo!pass123
  SQL_DBNAME: mydrivingDB